// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import CategoryController from "./category_controller.js"
application.register("category", CategoryController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ShowFollowingController from "./show_following_controller.js"
application.register("show-following", ShowFollowingController)
