version: "3.9"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=0 -Xms1G -Xmx1G
    ports:
      - 9200:9200

  redis:
    image: redis:6.0-alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis/data
   
  web:
    build: .
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOST: http://es:9200
      REDIS_URL: redis://redis:6379
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/gcv6
    ports:
      - "3000:3000"
    depends_on:
      - db
      - es
      - redis

volumes:
  db_data:
  es_data:
  redis_data:
